In [1]:
pip install pandas

Requirement already satisfied: pandas in /home/rgukt/.local/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /home/rgukt/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/rgukt/.local/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/rgukt/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/rgukt/.local/lib/python3.8/site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pandas as pd
data = pd.read_csv("/home/rgukt/Downloads/01.Data Cleaning and Preprocessing.csv")

In [25]:
data

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN

In [26]:
data.head()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      324 non-null    object
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF      323 non-null    float64
 18  BlackFlow-2      322 non-null    float64
 19  WeakWashF        323 non-null    float64
 20  SteamHeatF-3     322 non-null    float64
 21  T-Top-Chips-4    323 non-null    float64
 22  SulphidityL-4    173 non-null    float64
dtypes: float64(22), object(1)
memory usage: 58.3+ KB

In [28]:
data.isnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
320,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
321,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
322,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
323,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [30]:
data.shape

(324, 23)

In [31]:
data.describe()

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,324.000000,319.000000,307.000000,308.000000,323.000000,322.000000,322.000000,299.000000,323.000000,173.000000,...,323.000000,322.000000,322.000000,323.000000,323.000000,322.000000,323.000000,322.000000,323.000000,173.000000
mean,20.635370,14.347937,87.464456,1237.837614,258.164483,356.904295,324.020180,1.492010,591.732260,6.140410,...,66.668285,325.567820,300.525699,162.222322,873.828941,1175.917016,263.543068,49.696907,251.240087,30.411671
std,3.070036,1.499095,7.995012,100.593735,87.987452,9.209290,7.621402,0.105923,67.016351,0.081609,...,5.708587,4.609862,4.568484,14.160688,122.073521,149.334010,163.666942,4.551909,1.283432,0.701317
min,12.170000,9.983000,68.645000,0.000000,0.000000,339.168000,284.633000,1.182000,405.111000,5.890000,...,48.568000,318.051000,293.312000,113.922000,486.938000,838.948000,0.000000,35.510000,248.359000,29.010000
25%,18.382500,13.358000,81.823000,1193.215250,213.527000,350.241250,321.420000,1.431500,540.989500,6.089000,...,62.518000,321.385500,296.513250,153.032500,792.019500,1044.817500,134.649000,46.389750,250.312000,29.970000
50%,20.845000,14.308000,86.739000,1273.138500,271.792000,356.843000,325.669000,1.498000,592.895000,6.135000,...,67.429000,324.741000,299.126000,163.690000,865.254000,1150.221500,269.193000,50.277000,251.380000,30.370000
75%,23.032500,15.517000,92.372000,1289.196000,321.680000,362.242250,329.175000,1.560500,639.480500,6.199000,...,71.522000,329.845250,304.244750,172.555000,965.286500,1319.021250,405.563000,53.294250,252.323500,30.820000
max,27.600000,16.958000,121.717000,1351.240000,419.014000,399.135000,337.012000,1.747000,731.394000,6.340000,...,76.147000,333.854000,311.146000,189.268000,1226.277000,1395.767000,715.715000,63.332000,254.122000,32.840000

In [32]:
data.values

array([['31-00:00', 23.1, 16.52, ..., 54.612, 252.077, nan],
       ['31-01:00', 27.6, 16.81, ..., 46.603, 251.406, 29.11],
       ['31-02:00', 23.19, 16.709, ..., 51.795, 251.335, nan],
       ...,
       ['9-20:00', 23.01, 12.55, ..., 45.549, 252.438, nan],
       ['9-21:00', 24.32, 13.083, ..., 43.725, 253.176, 31.13],
       ['9-22:00', 25.75, 13.417, ..., 43.84, 253.216, nan]], dtype=object)

In [33]:
data.columns

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 '],
      dtype='object')

In [34]:
data.index

RangeIndex(start=0, stop=324, step=1)

# SORTING

In [35]:
data.sort_values("BlowFlow")

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
182,7-13:00,23.83,14.227,NaN,0.000,220.074,352.981,323.718,1.416,594.970,...,62.476,321.062,296.846,158.196,977.152,1092.896,81.065,51.821,249.353,NaN
281,11-16:00,24.41,11.242,80.458,954.092,365.583,342.403,302.669,1.556,546.509,...,68.806,328.581,306.169,157.026,734.945,1384.979,143.417,39.700,252.479,30.150
279,11-14:00,21.27,11.383,84.165,981.920,342.858,352.315,322.292,1.553,592.539,...,73.134,333.596,310.487,171.004,940.938,1375.202,189.529,52.600,251.797,30.400
280,11-15:00,23.74,11.667,88.130,990.724,349.088,349.697,311.997,1.555,579.875,...,72.092,332.637,309.538,168.574,973.897,1373.252,81.375,46.994,252.021,NaN
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.080,1.604,471.537,...,57.260,330.293,304.958,136.358,1067.280,1346.973,237.346,40.713,252.545,30.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
208,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
315,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
316,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580

In [38]:
data["ChipRate"]

0      16.520
1      16.810
2      16.709
3      16.478
4      15.618
        ...
319    12.667
320    12.558
321    12.550
322    13.083
323    13.417
Name: ChipRate, Length: 324, dtype: float64

In [36]:
data.sort_values("BlowFlow",ascending=False)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
311,31-09:00,22.60,13.875,95.720,1351.240,383.731,347.683,322.363,1.480,541.728,...,62.860,329.580,304.970,163.512,865.051,1319.664,118.240,45.992,251.284,NaN
10,31-09:00,22.60,13.875,95.720,1351.240,383.731,347.683,322.363,1.480,541.728,...,62.860,329.580,304.970,163.512,865.051,1319.664,118.240,45.992,251.284,NaN
309,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
310,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
208,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
315,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
316,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580

In [41]:
data.sort_values(["BlowFlow","ChipRate"])

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
182,7-13:00,23.83,14.227,NaN,0.000,220.074,352.981,323.718,1.416,594.970,...,62.476,321.062,296.846,158.196,977.152,1092.896,81.065,51.821,249.353,NaN
281,11-16:00,24.41,11.242,80.458,954.092,365.583,342.403,302.669,1.556,546.509,...,68.806,328.581,306.169,157.026,734.945,1384.979,143.417,39.700,252.479,30.150
279,11-14:00,21.27,11.383,84.165,981.920,342.858,352.315,322.292,1.553,592.539,...,73.134,333.596,310.487,171.004,940.938,1375.202,189.529,52.600,251.797,30.400
280,11-15:00,23.74,11.667,88.130,990.724,349.088,349.697,311.997,1.555,579.875,...,72.092,332.637,309.538,168.574,973.897,1373.252,81.375,46.994,252.021,NaN
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.080,1.604,471.537,...,57.260,330.293,304.958,136.358,1067.280,1346.973,237.346,40.713,252.545,30.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,7-17:00,20.05,13.950,NaN,NaN,177.994,356.716,325.924,NaN,633.280,...,66.888,320.295,295.975,164.581,919.433,1109.266,0.000,53.057,248.796,30.280
181,7-12:00,24.18,14.064,NaN,NaN,226.825,351.807,322.534,1.348,568.685,...,55.282,319.266,295.585,146.355,934.326,1093.351,39.037,50.132,250.465,29.880
185,7-16:00,19.46,14.467,NaN,NaN,183.323,356.777,326.310,1.428,651.767,...,67.219,320.086,294.877,167.048,1031.168,1092.960,178.637,54.201,248.547,29.530
206,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252

In [37]:
data.sort_values(["BlowFlow","ChipRate"],ascending=[True,False])

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
182,7-13:00,23.83,14.227,NaN,0.000,220.074,352.981,323.718,1.416,594.970,...,62.476,321.062,296.846,158.196,977.152,1092.896,81.065,51.821,249.353,NaN
281,11-16:00,24.41,11.242,80.458,954.092,365.583,342.403,302.669,1.556,546.509,...,68.806,328.581,306.169,157.026,734.945,1384.979,143.417,39.700,252.479,30.150
279,11-14:00,21.27,11.383,84.165,981.920,342.858,352.315,322.292,1.553,592.539,...,73.134,333.596,310.487,171.004,940.938,1375.202,189.529,52.600,251.797,30.400
280,11-15:00,23.74,11.667,88.130,990.724,349.088,349.697,311.997,1.555,579.875,...,72.092,332.637,309.538,168.574,973.897,1373.252,81.375,46.994,252.021,NaN
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.080,1.604,471.537,...,57.260,330.293,304.958,136.358,1067.280,1346.973,237.346,40.713,252.545,30.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
316,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
205,8-12:00,16.20,11.075,NaN,NaN,0.000,376.857,326.809,1.620,594.218,...,69.004,330.088,306.610,167.811,NaN,1223.783,NaN,57.178,248.893,NaN
206,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252

In [39]:
data["ChipRate"]>14

0       True
1       True
2       True
3       True
4       True
       ...
319    False
320    False
321    False
322    False
323    False
Name: ChipRate, Length: 324, dtype: bool

In [42]:
data[data["ChipRate"]>14]

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
312,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,62.179,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292
313,31-11:00,26.62,15.467,84.447,1334.255,386.971,349.392,321.021,1.428,531.250,...,59.407,330.284,303.248,156.797,799.947,1299.782,118.901,46.597,251.721,NaN
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
318,4-17:00,18.20,16.283,83.508,1288.104,234.284,359.412,328.670,1.534,692.687,...,74.528,321.224,298.231,173.827,854.573,1174.267,62.077,50.653,252.474,NaN

In [43]:
data[data["ChipRate"]==14]

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
18,31-17:00,17.80,14.0,92.772,1204.489,61.783,353.562,330.481,1.532,623.209,...,67.845,331.632,304.889,182.998,909.810,1295.843,415.118,52.502,252.733,30.770
116,4-19:00,14.17,14.0,97.813,1296.018,41.057,359.340,328.212,1.540,701.080,...,74.319,320.499,296.230,182.323,811.849,997.515,0.000,54.210,252.265,NaN
165,6-20:00,22.10,14.0,92.320,1297.863,346.952,354.590,326.076,1.356,619.751,...,65.795,319.782,296.444,152.523,970.438,1049.396,166.084,43.421,250.271,30.619
271,11-06:00,20.57,14.0,89.028,1283.489,334.651,350.317,318.559,1.503,563.547,...,69.523,332.444,308.953,161.528,1021.606,1369.424,129.433,50.611,252.143,NaN

In [45]:
data["avg"]=data["ChipRate"]/data["BlowFlow"]

In [46]:
data["avg"]

0      0.014028
1      0.012655
2      0.012569
3      0.012344
4      0.011706
         ...
319    0.010751
320    0.010605
321    0.010559
322    0.010968
323    0.011310
Name: avg, Length: 324, dtype: float64

In [47]:
data.head()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706

In [48]:
data["BlowFlow"].max()

1351.24

In [49]:
data["BlowFlow"].min()

0.0

In [50]:
data["BlowFlow"].sum()

381253.98500000004

In [51]:
data["BlowFlow"].mean()

1237.8376136363638

In [52]:
data["BlowFlow"].median()

1273.1385

In [53]:
data["BlowFlow"].std()

100.59373480181519

In [54]:
data["BlowFlow"].var()

10119.099481377925

In [55]:
data["BlowFlow"].quantile()

1273.1385

In [56]:
data["BlowFlow"].mode()

0     1171.604
1     1177.607
2     1178.252
3     1184.119
4     1186.342
5     1188.517
6     1192.879
7     1243.688
8     1276.082
9     1288.104
10    1289.992
11    1294.158
12    1307.852
13    1328.360
14    1329.407
15    1330.104
16    1334.168
17    1334.255
18    1334.877
19    1334.892
20    1346.900
21    1351.240
Name: BlowFlow, dtype: float64

In [57]:
data["BlowFlow"].cumsum()

0        1177.607
1        2505.967
2        3835.374
3        5170.251
4        6504.419
          ...
319    376502.128
320    377686.247
321    378874.764
322    380067.643
323    381253.985
Name: BlowFlow, Length: 324, dtype: float64

In [58]:
data["BlowFlow"].cummax()

0      1177.607
1      1328.360
2      1329.407
3      1334.877
4      1334.877
         ...
319    1351.240
320    1351.240
321    1351.240
322    1351.240
323    1351.240
Name: BlowFlow, Length: 324, dtype: float64

In [59]:
data["BlowFlow"].cummin()

0      1177.607
1      1177.607
2      1177.607
3      1177.607
4      1177.607
         ...
319       0.000
320       0.000
321       0.000
322       0.000
323       0.000
Name: BlowFlow, Length: 324, dtype: float64

In [60]:
data["BlowFlow"].cumprod()

/home/rgukt/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)
/home/rgukt/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:57: RuntimeWarning: invalid value encountered in accumulate
  return bound(*args, **kwds)

0      1.177607e+03
1      1.564286e+06
2      2.079573e+09
3      2.775974e+12
4      3.703616e+15
           ...
319             NaN
320             NaN
321             NaN
322             NaN
323             NaN
Name: BlowFlow, Length: 324, dtype: float64

In [61]:
data.drop_duplicates

<bound method DataFrame.drop_duplicates of     Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0      31-00:00    23.10    16.520     121.717  1177.607      169.805
1      31-01:00    27.60    16.810      79.022  1328.360      341.327
2      31-02:00    23.19    16.709      79.562  1329.407      239.161
3      31-03:00    23.60    16.478      81.011  1334.877      213.527
4      31-04:00    22.90    15.618      93.244  1334.168      243.131
..          ...      ...       ...         ...       ...          ...
319    10-16:00    23.75    12.667      93.450  1178.252      276.955
320     9-19:00    19.80    12.558      94.352  1184.119      297.071
321     9-20:00    23.01    12.550      90.842  1188.517      289.826
322     9-21:00    24.32    13.083      88.910  1192.879      318.006
323     9-22:00    25.75    13.417      85.451  1186.342      248.312

     T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  Lower-HeatT-3  \
0          358.282         329.545  1.443       599.253  ...        329.432
1          351.050         329.067  1.549       537.201  ...        330.823
2          350.022         329.260  1.600       549.611  ...        329.140
3          350.938         331.142  1.604       623.362  ...        328.875
4          351.640         332.709    NaN       638.672  ...        328.352
..             ...             ...    ...           ...  ...            ...
319        347.286         310.970  1.523       513.956  ...        330.117
320        399.135         319.576  1.451       570.058  ...        330.848
321        373.633         314.591  1.457       549.306  ...        330.226
322        364.081         308.559  1.523       504.852  ...        327.346
323        356.289         310.482  1.474       497.375  ...        328.092

     Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   WeakWashF   \
0           303.099      175.964      1127.197      1319.039     257.325
1           304.879      163.202       665.975      1297.317     241.182
2           303.383      164.013       677.534      1327.072     237.272
3           302.254      181.487       767.853      1324.461     239.478
4           300.954      183.929       888.448      1343.424     215.372
..              ...          ...           ...           ...         ...
319         304.006      148.174      1027.201      1357.271     381.643
320         304.616      165.178       906.962      1311.177      25.494
321         304.686      160.841       887.125      1319.226       0.638
322         304.363      147.589       804.423      1320.225       0.000
323         304.093      144.218       828.328      1320.848       1.276

     SteamHeatF-3   T-Top-Chips-4   SulphidityL-4        avg
0           54.612         252.077             NaN  0.014028
1           46.603         251.406           29.11  0.012655
2           51.795         251.335             NaN  0.012569
3           54.846         250.312           29.02  0.012344
4           54.186         249.916           29.01  0.011706
..             ...             ...             ...       ...
319         45.264         252.947           30.86  0.010751
320         50.528         252.092           30.70  0.010605
321         45.549         252.438             NaN  0.010559
322         43.725         253.176           31.13  0.010968
323         43.840         253.216             NaN  0.011310

[324 rows x 24 columns]>

In [62]:
duplicates=data.drop_duplicates(subset=["BlowFlow","ChipRate"])

In [63]:
duplicates

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29,0.011815
299,12-10:00,24.98,NaN,85.034,1278.345,368.564,357.723,321.387,NaN,520.365,...,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47,NaN
300,12-11:00,21.00,NaN,88.013,1307.722,278.842,357.438,323.757,NaN,553.070,...,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,NaN,NaN
301,12-12:00,21.40,NaN,85.490,1255.986,273.484,361.365,322.689,NaN,590.199,...,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46,NaN
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,NaN,0.010775

In [64]:
duplicates["ChipRate"].value_counts(sort=True)

ChipRate
15.800    5
14.000    4
14.142    3
15.225    3
16.283    3
         ..
16.455    1
16.625    1
15.425    1
13.250    1
14.308    1
Name: count, Length: 243, dtype: int64

In [65]:
data[data["ChipRate"]==14]["BlowFlow"].mean()

1270.46475

In [66]:
data.groupby("ChipRate")["BlowFlow"].mean()

ChipRate
9.983     1027.485
10.625    1010.855
10.833    1202.818
10.933    1038.618
10.942    1241.142
            ...
16.817    1237.844
16.825    1246.387
16.833    1236.911
16.867    1284.849
16.958    1230.776
Name: BlowFlow, Length: 243, dtype: float64

In [67]:
data.groupby("ChipRate")["BlowFlow"].agg(["max","min","sum"])

               max       min       sum
ChipRate
9.983     1027.485  1027.485  1027.485
10.625    1010.855  1010.855  1010.855
10.833    1202.818  1202.818  1202.818
10.933    1038.618  1038.618  1038.618
10.942    1241.142  1241.142  1241.142
...            ...       ...       ...
16.817    1237.844  1237.844  1237.844
16.825    1246.387  1246.387  1246.387
16.833    1236.911  1236.911  1236.911
16.867    1284.849  1284.849  1284.849
16.958    1230.776  1230.776  1230.776

[243 rows x 3 columns]

In [69]:
data.pivot_table(values="ChipRate",index="BlowFlow")

          ChipRate
BlowFlow
0.000       14.227
954.092     11.242
981.920     11.383
990.724     11.667
998.153     10.967
...            ...
1334.255    15.467
1334.877    16.478
1334.892    13.850
1346.900    14.233
1351.240    13.875

[283 rows x 1 columns]

In [70]:
data.pivot_table(values="ChipRate",index="BlowFlow",columns="Y-Kappa")

Y-Kappa,12.17,12.48,12.81,13.48,13.49,14.17,14.23,14.39,14.53,14.80,...,25.52,25.56,25.75,26.02,26.10,26.50,26.62,27.10,27.20,27.60
BlowFlow,,,,,,,,,,,,,,,,,,,,,
0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954.092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
981.920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998.153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334.255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.467,NaN,NaN,NaN
1334.877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1334.892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1346.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1351.240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
import numpy as np
data.pivot_table(values="ChipRate",index="BlowFlow",aggfunc=np.median)

          ChipRate
BlowFlow
0.000       14.227
954.092     11.242
981.920     11.383
990.724     11.667
998.153     10.967
...            ...
1334.255    15.467
1334.877    16.478
1334.892    13.850
1346.900    14.233
1351.240    13.875

[283 rows x 1 columns]

In [73]:
data.pivot_table(values="ChipRate",index="BlowFlow",columns="Y-Kappa",fill_value=0)

Y-Kappa,12.17,12.48,12.81,13.48,13.49,14.17,14.23,14.39,14.53,14.80,...,25.52,25.56,25.75,26.02,26.10,26.50,26.62,27.10,27.20,27.60
BlowFlow,,,,,,,,,,,,,,,,,,,,,
0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
954.092,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
981.920,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
990.724,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
998.153,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334.255,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.467,0.0,0.0,0.0
1334.877,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
1334.892,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
1346.900,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0
1351.240,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0

In [76]:
data.pivot_table(values="ChipRate",index="BlowFlow",columns="Y-Kappa",margins=True)

Y-Kappa,12.17,12.48,12.81,13.48,13.49,14.17,14.23,14.39,14.53,14.8,...,25.56,25.75,26.02,26.1,26.5,26.62,27.1,27.2,27.6,All
BlowFlow,,,,,,,,,,,,,,,,,,,,,
0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.227000
954.092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.242000
981.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.383000
990.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.667000
998.153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.967000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334.877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.478000
1334.892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.850000
1346.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.233000
1351.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.875000
All,12.667,15.95,10.942,13.633,13.7,14.0,15.35,11.642,10.833,16.125,...,14.9,13.417,15.8,15.083,16.3,15.467,13.558,16.083,16.81,14.402898

In [77]:
data.columns

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 ', 'avg'],
      dtype='object')

In [78]:
data.index

RangeIndex(start=0, stop=324, step=1)

In [80]:
data.ind=data.set_index("Observation")

<ipython-input-80-cb98e0a94c5e>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.ind=data.set_index("Observation")

In [81]:
data.ind

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
Observation,,,,,,,,,,,,,,,,,,,,,
31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,NaN,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028
31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,NaN,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,6.110,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,6.068,...,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86,0.010751
9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,6.190,...,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70,0.010605
9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,NaN,...,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN,0.010559
9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,6.128,...,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13,0.010968
9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,NaN,...,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN,0.011310

In [82]:
data.ind.reset_index(drop=True)

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,NaN,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
2,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,NaN,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
4,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,6.110,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,6.068,...,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86,0.010751
320,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,6.190,...,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70,0.010605
321,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,NaN,...,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN,0.010559
322,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,6.128,...,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13,0.010968
323,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,NaN,...,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN,0.011310

In [74]:
data[4:14]

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.010,0.011706
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.340,0.013102
6,1-09:00,13.49,13.700,98.186,1243.688,116.275,346.208,326.982,1.434,696.766,...,322.982,296.080,182.018,784.281,929.527,201.272,58.118,248.741,NaN,0.011016
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220,0.010781
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN,0.010567
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210,0.010375
10,31-09:00,22.60,13.875,95.720,1351.240,383.731,347.683,322.363,1.480,541.728,...,329.580,304.970,163.512,865.051,1319.664,118.240,45.992,251.284,NaN,0.010268
11,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292,0.010613
12,31-11:00,26.62,15.467,84.447,1334.255,386.971,349.392,321.021,1.428,531.250,...,330.284,303.248,156.797,799.947,1299.782,118.901,46.597,251.721,NaN,0.011592
13,31-12:00,27.20,16.083,82.839,1332.331,366.855,350.094,327.439,1.486,527.893,...,330.023,302.883,160.562,771.158,1299.974,153.647,47.175,251.767,30.180,0.012071

In [75]:
data[7:13]

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220,0.010781
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN,0.010567
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210,0.010375
10,31-09:00,22.60,13.875,95.720,1351.240,383.731,347.683,322.363,1.480,541.728,...,329.580,304.970,163.512,865.051,1319.664,118.240,45.992,251.284,NaN,0.010268
11,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292,0.010613
12,31-11:00,26.62,15.467,84.447,1334.255,386.971,349.392,321.021,1.428,531.250,...,330.284,303.248,156.797,799.947,1299.782,118.901,46.597,251.721,NaN,0.011592

In [83]:
data[::-1]

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN,0.011310
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13,0.010968
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN,0.010559
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70,0.010605
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86,0.010751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028

In [84]:
data.iloc[2:5,7:13]

,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,AA-Wood-4,ChipMoisture-4
2,329.260,1.600,549.611,NaN,16.559,44.495
3,331.142,1.604,623.362,6.054,16.562,45.592
4,332.709,NaN,638.672,6.110,16.677,45.512

In [85]:
data.isna()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
320,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
321,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
322,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
323,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [86]:
data.isna().any()

Observation        False
Y-Kappa            False
ChipRate            True
BF-CMratio          True
BlowFlow            True
ChipLevel4          True
T-upperExt-2        True
T-lowerExt-2        True
UCZAA               True
WhiteFlow-4         True
AAWhiteSt-4         True
AA-Wood-4           True
ChipMoisture-4      True
SteamFlow-4         True
Lower-HeatT-3       True
Upper-HeatT-3       True
ChipMass-4          True
WeakLiquorF         True
BlackFlow-2         True
WeakWashF           True
SteamHeatF-3        True
T-Top-Chips-4       True
SulphidityL-4       True
avg                 True
dtype: bool

In [87]:
data.isna().sum()

Observation          0
Y-Kappa              0
ChipRate             5
BF-CMratio          17
BlowFlow            16
ChipLevel4           1
T-upperExt-2         2
T-lowerExt-2         2
UCZAA               25
WhiteFlow-4          1
AAWhiteSt-4        151
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        2
Upper-HeatT-3        2
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          2
WeakWashF            1
SteamHeatF-3         2
T-Top-Chips-4        1
SulphidityL-4      151
avg                 19
dtype: int64

In [88]:
data.dropna()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110,0.012655
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020,0.012344
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.340,0.013102
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220,0.010781
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210,0.010375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292,0.010613
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320,0.013028
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860,0.010751
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700,0.010605
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130,0.010968

In [90]:
data.fillna(0)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,0.00,0.014028
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,0.00,0.012569
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,0.000,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86,0.010751
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70,0.010605
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,0.00,0.010559
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13,0.010968
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,0.00,0.011310

In [91]:
data.isnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
320,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
321,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
322,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
323,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [92]:
data.dropna(axis=1)

    Observation  Y-Kappa
0      31-00:00    23.10
1      31-01:00    27.60
2      31-02:00    23.19
3      31-03:00    23.60
4      31-04:00    22.90
..          ...      ...
319    10-16:00    23.75
320     9-19:00    19.80
321     9-20:00    23.01
322     9-21:00    24.32
323     9-22:00    25.75

[324 rows x 2 columns]

In [93]:
data.drop_duplicates()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4,avg
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN,0.014028
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11,0.012655
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN,0.012569
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02,0.012344
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01,0.011706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,12-09:00,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,...,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29,0.011815
299,12-10:00,24.98,NaN,85.034,1278.345,368.564,357.723,321.387,NaN,520.365,...,332.523,307.169,151.544,905.639,1344.469,418.979,48.135,251.614,30.47,NaN
300,12-11:00,21.00,NaN,88.013,1307.722,278.842,357.438,323.757,NaN,553.070,...,331.263,306.400,157.954,908.691,1344.588,462.712,54.373,251.197,NaN,NaN
301,12-12:00,21.40,NaN,85.490,1255.986,273.484,361.365,322.689,NaN,590.199,...,333.032,308.732,174.069,986.206,1348.747,457.313,53.194,251.324,30.46,NaN
307,31-05:00,20.89,14.308,94.172,1327.832,251.120,351.263,332.485,1.522,631.514,...,328.699,300.706,180.229,903.605,1323.082,232.729,54.503,250.084,NaN,0.010775